@base = http://localhost:3333/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTc2MDU3MDMxOCwiZXhwIjoxNzYwNjU2NzE4fQ.zq7rzBYtd0yDbksfoEVgFUTkz779TUe3MTE20dkgtBs

### Health
GET {{base}}/health


### Login  (copiar o token da resposta e colocar em cima)
POST {{base}}/auth/login
Content-Type: application/json

{"email":"daniel2@test.com","password":"12345678"}


### Me
GET {{base}}/auth/me
Authorization: Bearer {{token}}


### List Vehicles
GET {{base}}/vehicles
Authorization: Bearer {{token}}


### Create Vehicle 
POST {{base}}/vehicles
Authorization: Bearer {{token}}
Content-Type: application/json

{"plate":"AA-00-ZZ","brand":"Harley Davidson","model":"Street Bob","photoUrl":"https://static1.hotcarsimages.com/wordpress/wp-content/uploads/2023/10/23-fxbb-street-bob-beauty-bc-0009-edit-1.jpg"}


### Update Vehicle (PATCH)
PATCH {{base}}/vehicles/3
Authorization: Bearer {{token}}
Content-Type: application/json

{"model":"Street Bob (2020)"}


### Delete Vehicle
DELETE {{base}}/vehicles/1
Authorization: Bearer {{token}}
